/* Screen locations shown on the map. Add or edit one object per screen.
   status: "active" (installed, terracotta pin) | "soon" (planned, navy pin)
   Coordinates: decimal degrees (Google Maps → right-click → copy the numbers).
   Planned pins are approximate placements inside each district; replace them
   with real addresses as screens are installed. */
window.TIVY_LOCATIONS = [
  {
    id: "samgori-1",
    lat: 41.671396,
    lng: 44.875710,
    title: "ბოგდან ხმელნიცკის ქ. #3",
    titleEn: "Bogdan Khmelnitsky St. 3",
    district: "ქვემო სამგორი",
    districtEn: "Kvemo Samgori",
    screens: 1,
    status: "active",
    maps: "https://maps.app.goo.gl/vz2U4sJGw4nN8M9q9"
  },
  // ---- planned locations (49) ----
  { id: "saburtalo-1", lat: 41.722562, lng: 44.741414, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-2", lat: 41.73166, lng: 44.745159, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-3", lat: 41.720395, lng: 44.732851, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-4", lat: 41.722138, lng: 44.725119, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-5", lat: 41.729912, lng: 44.738938, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-6", lat: 41.713268, lng: 44.749451, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-7", lat: 41.72367, lng: 44.75223, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-8", lat: 41.725862, lng: 44.747572, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-9", lat: 41.721402, lng: 44.742163, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-10", lat: 41.727848, lng: 44.723347, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-11", lat: 41.740239, lng: 44.732745, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-12", lat: 41.721943, lng: 44.752634, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-13", lat: 41.720587, lng: 44.740885, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-14", lat: 41.727893, lng: 44.757058, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-15", lat: 41.716488, lng: 44.736306, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-16", lat: 41.728528, lng: 44.722958, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-17", lat: 41.735525, lng: 44.733005, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-18", lat: 41.713156, lng: 44.751295, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-19", lat: 41.726484, lng: 44.745841, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-20", lat: 41.727956, lng: 44.753369, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-21", lat: 41.719485, lng: 44.731796, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-22", lat: 41.730238, lng: 44.728184, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-23", lat: 41.732185, lng: 44.741191, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-24", lat: 41.718277, lng: 44.762002, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "saburtalo-25", lat: 41.727024, lng: 44.743607, title: "საბურთალო", titleEn: "Saburtalo", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-1", lat: 41.713282, lng: 44.758889, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-2", lat: 41.703099, lng: 44.758114, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-3", lat: 41.708172, lng: 44.769823, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-4", lat: 41.694931, lng: 44.747691, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-5", lat: 41.71591, lng: 44.759168, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-6", lat: 41.71213, lng: 44.76202, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-7", lat: 41.706148, lng: 44.75551, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-8", lat: 41.712879, lng: 44.769299, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-9", lat: 41.70374, lng: 44.752115, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-10", lat: 41.712715, lng: 44.760626, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-11", lat: 41.703167, lng: 44.768224, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-12", lat: 41.705618, lng: 44.76189, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-13", lat: 41.715541, lng: 44.766554, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-14", lat: 41.698744, lng: 44.747698, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-15", lat: 41.707748, lng: 44.757387, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-16", lat: 41.704349, lng: 44.758874, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-17", lat: 41.699148, lng: 44.758292, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vake-18", lat: 41.707923, lng: 44.765962, title: "ვაკე", titleEn: "Vake", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vera-1", lat: 41.7038, lng: 44.785943, title: "ვერა", titleEn: "Vera", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "vera-2", lat: 41.700386, lng: 44.779187, title: "ვერა", titleEn: "Vera", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "dighomi-1", lat: 41.770544, lng: 44.761134, title: "დიღომი", titleEn: "Dighomi", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "dighomi-2", lat: 41.773512, lng: 44.760824, title: "დიღომი", titleEn: "Dighomi", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "isani-1", lat: 41.687563, lng: 44.828645, title: "ისანი", titleEn: "Isani", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" },
  { id: "chugureti-1", lat: 41.713446, lng: 44.806147, title: "ჩუღურეთი", titleEn: "Chugureti", district: "დაგეგმილი მისამართი", districtEn: "Planned address", screens: 1, status: "soon" }
];
